site_name: MocapForAll Manual
site_url: https://Akiya-Research-Institute.github.io/MocapForAll-Manual/
site_author: Kenji Asaba
site_description: >-
  Official documentation of MocapForAll, a Windows application that captures motion of a person with multiple webcams. This page explains how to set it up and use it with VR and game engines.
copyright: Copyright &copy; 2022 Akiya Research Institute, Inc. All Rights Reserved

site_dir: ../docs

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  # custom_dir: overrides  
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: M PLUS 1
    code: M PLUS 1 Code
  language: en
  favicon: images/favicon.png
  logo: images/logo.png
  features:
    - navigation.instant
    - navigation.tracking    
    # - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    
extra:
  alternate:
    - name: English
      link: /MocapForAll-Manual/en/ 
      lang: en
    - name: 日本語
      link: /MocapForAll-Manual/ja/
      lang: ja
  analytics:
    provider: google
    property: UA-2709176-10
  social:
    - icon: fontawesome/solid/home
      link: https://vrlab.akiya-souken.co.jp/
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/channel/UC7t4amWNvquSy_ODcGZ4R0g
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Akiya_Souken_VR
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/VvkHcdueUW
    - icon: fontawesome/brands/github 
      link: https://github.com/Akiya-Research-Institute
    - icon: fontawesome/brands/steam
      link: https://store.steampowered.com/app/1759710/MocapForAll/
    - icon: fontawesome/solid/store-alt
      link: https://akiya-souken.booth.pm/

    # - icon: images/logo.png
    #   link: https://vrlab.akiya-souken.co.jp/
  # generator: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html

plugins: []
